params:
  assets:
    favicon: "/img/favicon.png"
  social: true
  disableThemeToggle: false
  defaultTheme: dark
  homeInfoParams:
    Title: "Welcome / Mauya / Siyalemukela"
    Content: Welcome to my tech blog where I share insights into data communications, distributed systems, machine learning, Event-Driven Systems, Microservices, distributed energy systems, open source software, design science research, and software development.
  socialIcons:
    - name: twitter
      url: "https://twitter.com/mapfumo"
    - name: github
      url: "https://github.com/mapfumo"
    - name: email
      url: "mailto:mapfumo@icloud.com"
  cover:
    linkFullImages: true
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
